
import = ["~/.config/alacritty/rice-colors.toml"]

live_config_reload = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
blur = true
dynamic_padding = true

[window.padding]
x = 15
y = 15

[font]
size = 10

builtin_box_drawing = true

normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
