transmission-daemon &
transmission-rss -f &
mpd &
mpDris2 &

dunst &
sxhkd &
udiskie & 
xbanish &
xsetroot -cursor_name left_ptr &
srdb -load ~/.config/X11/xresources &
xmodmap ~/.config/X11/modmap &
exec bspwm